%Image::ExifTool::UserDefined = (
  'Image::ExifTool::XMP::xmp' => {
    VBCOriginalName => { Writable => 'string' },
    VBCOriginalSize => { Writable => 'integer' },
    VBCQuality => { Writable => 'string' },
    VBCOriginalBitrate => { Writable => 'string' },
    VBCJsonNotes => { Writable => 'string' },
    VBCEncoder => { Writable => 'string' },
    VBCFinishedAt => { Writable => 'date' },
    VBCSourceParts => { Writable => 'string' },
  },
);

1;  # end
